### ISSUE TITLE
error while compiling exanic-devkit-extended-memory-write.c

### ISSUE THREAD

**Issue by ahdzesq** [exablaze-oss/exanic-software#23]
The compiler returns this error:

> exanic-devkit-extended-memory-write.c:19:5: error: ‘for’ loop initial declarations are only allowed in C99 mode
>      for (int i = 0; i < BUFFER_SIZE; i++)

**Comment by QiweiWen** [comment]
Hi,

could you try one of two things:

option 1: 
open `examples/devkit/Makefile`, append ` -std=gnu99` to `CFLAGS`, and try again

option 2:
change `for (int i = 0; i < BUFFER_SIZE; i++)` to the following: `int i; for (i = 0; i < BUFFER_SIZE; i++)`
